// src/components/SpotifyPlayer.svelte
<script lang="ts">
    import { useQuery } from "@sveltestack/svelte-query";
    import type { SpotifyData } from "../../lib/types";

    const queryResult = useQuery<SpotifyData>("repoData", () =>
        fetch("/api/now-playing").then((res) => res.json())
    );
</script>

{#if $queryResult.data && $queryResult.data.isPlaying}
    <a class="player" href={$queryResult.data.songUrl ?? ""} target="_blank">
        <div class="text-container">
            <span>Now playing</span>
            <span>
                {$queryResult.data.title} - {$queryResult.data.artist}
            </span>
        </div>

        {#if $queryResult.data.albumImage}
            <img
                src={$queryResult.data.albumImage.url}
                width={$queryResult.data.albumImage.width}
                height={$queryResult.data.albumImage.height}
                alt={`Album cover of ${
                    $queryResult.data.album ?? "the album"
                } by ${$queryResult.data.artist ?? "the artist"}`}
            />
        {/if}
    </a>
{:else}
    <span class="player">
        <div class="text-container">
            <span>Offline</span>
            <span>Spotify</span>
        </div>

        <div class="image-placeholder">
            <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="currentColor"
                viewBox="0 0 256 256"
            >
                <path
                    d="M179.1,108.3a112.1,112.1,0,0,0-102.3.1"
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="16"
                />
                <path
                    d="M164.3,136.7a79.9,79.9,0,0,0-72.7.1"
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="16"
                />
                <path
                    d="M149.5,165.1A47.3,47.3,0,0,0,128,160a48.7,48.7,0,0,0-21.6,5.1"
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="16"
                />
            </svg>
        </div>
    </span>
{/if}

<style lang="scss">
    .player {
        max-width: 100%;

        display: flex;
        flex-direction: row;
        gap: var(--spaces-2);
        border-radius: var(--radii-md);
        line-height: 24px;
        letter-spacing: -0.01em;

        .text-container {
            min-width: 0;
            max-width: 100%;

            display: flex;
            flex-direction: column;
            height: 3rem;
            align-items: flex-end;
            justify-content: center;
            text-align: end;

            > span {
                max-width: 100%;

                font-family: var(--fonts-display);
                font-weight: var(--fontWeights-regular);
                font-size: smaller;
                line-height: 1.5;
                text-transform: uppercase;
                overflow: hidden;
                white-space: nowrap;
                text-overflow: ellipsis;

                &:first-child {
                    font-weight: var(--fontWeights-bold);
                }
            }
        }

        img {
            border-radius: var(--radii-full);
            width: 3rem;
            height: 3rem;
        }

        .image-placeholder {
            border-radius: var(--radii-full);
            width: 3rem;
            height: 3rem;
            background: rgb(var(--colors-green400));
        }

        .svg {
            width: 100%;
            height: 100%;
        }
    }
</style>

// src/components/SpotifyPlayer.tsx
import { useState } from "react";
import type { Fetcher } from "swr";
import useSWR from "swr";
import type { SpotifyData } from "../../lib/types";
import { css } from "../stitches.config";

const link = css({
    maxWidth: "100%",

    display: "flex",
    flexDirection: "row",
    gap: "$2",
    borderRadius: "$md",
    lineHeight: "24px",
    letterSpacing: "-.01em",
});

const textContainer = css({
    maxWidth: "100%",

    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    height: "3rem",
    alignItems: "flex-end",
    justifyContent: "center",
    textAlign: "end",

    "& > span": {
        maxWidth: "100%",

        fontFamily: "$display",
        fontWeight: "$regular",
        fontSize: "smaller",
        lineHeight: 1.5,
        textTransform: "uppercase",
        overflow: "hidden",
        whiteSpace: "nowrap",
        textOverflow: "ellipsis",

        "&:first-child": { fontWeight: "$bold" },
    },
});

const image = css({
    borderRadius: "$full",
    width: "3rem",
    height: "3rem",
});

const imagePlaceholder = css({
    borderRadius: "$full",
    width: "3rem",
    height: "3rem",
    background: "rgb($green400)",
});
const svg = css({
    width: "100%",
    height: "100%",
});

const SpotifyPlayer = () => {
    // const fetcher = async (url: string): Promise<SpotifyData> => {
    //     const res = await fetch(url);
    //     return res.json();
    // };

    // const [data, setData] = useState<SpotifyData | null>(null);

    // const interval = setInterval(async () => {
    //     const fetchData = await fetcher("/.netlify/functions/now-playing");
    //     setData(fetchData);
    // }, 30 * 1000);

    const fetcher: Fetcher<SpotifyData> = async (url: string) => {
        const res = await fetch(url);
        return res.json();
    };

    const { data, error } = useSWR("/.netlify/functions/now-playing", fetcher, {
        refreshInterval: 30000,
        // revalidateIfStale: false,
        // revalidateOnFocus: false,
        // revalidateOnReconnect: false,
    });

    const {
        isPlaying,
        title,
        artist,
        album,
        albumImage,
        songUrl,
    }: SpotifyData = data ?? {
        isPlaying: false,
    };

    return isPlaying ? (
        <a className={link()} href={songUrl ?? ""} target="_blank">
            <div className={textContainer()}>
                <span>Now playing</span>
                <span>
                    {title} - {artist}
                </span>
            </div>

            {albumImage && (
                <img
                    className={image()}
                    src={albumImage.url}
                    width={albumImage.width}
                    height={albumImage.height}
                    alt={`Album cover of ${album ?? "the album"} by ${
                        artist ?? "the artist"
                    }`}
                />
            )}
        </a>
    ) : (
        <span className={link()}>
            <div className={textContainer()}>
                <span>Offline</span>
                <span>Spotify</span>
            </div>

            <div className={imagePlaceholder()}>
                <svg
                    className={svg()}
                    xmlns="http://www.w3.org/2000/svg"
                    fill="currentColor"
                    viewBox="0 0 256 256"
                >
                    <path
                        d="M179.1,108.3a112.1,112.1,0,0,0-102.3.1"
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="16"
                    ></path>
                    <path
                        d="M164.3,136.7a79.9,79.9,0,0,0-72.7.1"
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="16"
                    ></path>
                    <path
                        d="M149.5,165.1A47.3,47.3,0,0,0,128,160a48.7,48.7,0,0,0-21.6,5.1"
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="16"
                    ></path>
                </svg>
            </div>
        </span>
    );
};

export default SpotifyPlayer;
